apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
spec:
  hard:
    requests.cpu: "2000m"
    requests.memory: 4Gi
    requests.storage: 35Gi
    limits.cpu: "2000m"
    limits.memory: 4Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default
spec:
  limits:
    - default:
        cpu: "100m"
        memory: "100Mi"
      defaultRequest:
        cpu: "100m"
        memory: "100Mi"
      type: Container
