# Default values for todos-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



wavefront:
  apiToken: ""
  uri: ""
  application:
    name: ""
imageRepository: ""
ingressUrl: ""
namespace: ""
